# Generated by Django 5.0.7 on 2024-07-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='password',
            field=models.CharField(blank=True, default='admin', max_length=150, null=True),
        ),
    ]
